sudo: false

language: node_js
node_js:
  - 6

before_install:
  - yarn add codecov.io coveralls flow

script:
  - yarn run test:coverage
  - yarn run flow
  - yarn run lint
  - yarn run lint:style

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
