// flow-typed signature: 992be3f2691bdad9dd9c584c3945cf2d
// flow-typed version: <<STUB>>/flight-common_vfile:///home/barmston/src/flight-common//flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flight-common'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flight-common' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flight-common/lib/components/AuthorizedComponent' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/Clipboard' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/CookieBanner' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/CustomerSupport' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/FlightPanel' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/Footer' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/Header' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/HelpPopover' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/Icon' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/index' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/LicensableTable' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/LicenseLink' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/LicensesLinks' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/LinkContainer' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/Links' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/LoadingPage' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/MissingNotice' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/nav/NavCounter' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/nav/NavCounterBadge' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/nav/NavOverlay' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/nav/NavOverlayEntry' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/PageHeader' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/pages/AboutPage' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/pages/index' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/pages/PrivacyPolicyPage' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/pages/SecurityPage' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/pages/TermsOfServicePage' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/PrivacyPolicy' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/StandardModal' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/StatefulButton' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/TimeAgo' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/TooltipTrigger' {
  declare module.exports: any;
}

declare module 'flight-common/lib/components/WrappedWithPara' {
  declare module.exports: any;
}

declare module 'flight-common/lib/index' {
  declare module.exports: any;
}

declare module 'flight-common/lib/modules/notification/actions' {
  declare module.exports: any;
}

declare module 'flight-common/lib/modules/notification/actionTypes' {
  declare module.exports: any;
}

declare module 'flight-common/lib/modules/notification/components/NotificationModal' {
  declare module.exports: any;
}

declare module 'flight-common/lib/modules/notification/components/NotificationModals' {
  declare module.exports: any;
}

declare module 'flight-common/lib/modules/notification/errorMessageCustomization' {
  declare module.exports: any;
}

declare module 'flight-common/lib/modules/notification/messageGeneration' {
  declare module.exports: any;
}

declare module 'flight-common/lib/modules/notification/MessageGenerator' {
  declare module.exports: any;
}

declare module 'flight-common/lib/modules/notification/MessageGeneratorsMap' {
  declare module.exports: any;
}

declare module 'flight-common/lib/modules/notification/reducer' {
  declare module.exports: any;
}

declare module 'flight-common/lib/utils/console' {
  declare module.exports: any;
}

declare module 'flight-common/lib/utils/licensables' {
  declare module.exports: any;
}

declare module 'flight-common/lib/utils/momentConfiguration' {
  declare module.exports: any;
}

declare module 'flight-common/lib/utils/silenceEvents' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/AuthorizedComponent' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/Clipboard' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/CookieBanner' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/CustomerSupport' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/FlightPanel' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/Footer' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/Header' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/HelpPopover' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/Icon' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/index' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/LicensableTable' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/LicenseLink' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/LicensesLinks' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/LinkContainer' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/Links' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/LoadingPage' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/MissingNotice' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/nav/NavCounter' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/nav/NavCounterBadge' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/nav/NavOverlay' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/nav/NavOverlayEntry' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/PageHeader' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/pages/AboutPage' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/pages/index' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/pages/PrivacyPolicyPage' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/pages/SecurityPage' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/pages/TermsOfServicePage' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/PrivacyPolicy' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/StandardModal' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/StatefulButton' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/TimeAgo' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/TooltipTrigger' {
  declare module.exports: any;
}

declare module 'flight-common/src/components/WrappedWithPara' {
  declare module.exports: any;
}

declare module 'flight-common/src/index' {
  declare module.exports: any;
}

declare module 'flight-common/src/modules/notification/actions' {
  declare module.exports: any;
}

declare module 'flight-common/src/modules/notification/actionTypes' {
  declare module.exports: any;
}

declare module 'flight-common/src/modules/notification/components/NotificationModal' {
  declare module.exports: any;
}

declare module 'flight-common/src/modules/notification/components/NotificationModals' {
  declare module.exports: any;
}

declare module 'flight-common/src/modules/notification/errorMessageCustomization' {
  declare module.exports: any;
}

declare module 'flight-common/src/modules/notification/messageGeneration' {
  declare module.exports: any;
}

declare module 'flight-common/src/modules/notification/MessageGenerator' {
  declare module.exports: any;
}

declare module 'flight-common/src/modules/notification/MessageGeneratorsMap' {
  declare module.exports: any;
}

declare module 'flight-common/src/modules/notification/reducer' {
  declare module.exports: any;
}

declare module 'flight-common/src/utils/console' {
  declare module.exports: any;
}

declare module 'flight-common/src/utils/licensables' {
  declare module.exports: any;
}

declare module 'flight-common/src/utils/momentConfiguration' {
  declare module.exports: any;
}

declare module 'flight-common/src/utils/silenceEvents' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flight-common/index' {
  declare module.exports: $Exports<'flight-common'>;
}
declare module 'flight-common/index.js' {
  declare module.exports: $Exports<'flight-common'>;
}
declare module 'flight-common/lib/components/AuthorizedComponent.js' {
  declare module.exports: $Exports<'flight-common/lib/components/AuthorizedComponent'>;
}
declare module 'flight-common/lib/components/Clipboard.js' {
  declare module.exports: $Exports<'flight-common/lib/components/Clipboard'>;
}
declare module 'flight-common/lib/components/CookieBanner.js' {
  declare module.exports: $Exports<'flight-common/lib/components/CookieBanner'>;
}
declare module 'flight-common/lib/components/CustomerSupport.js' {
  declare module.exports: $Exports<'flight-common/lib/components/CustomerSupport'>;
}
declare module 'flight-common/lib/components/FlightPanel.js' {
  declare module.exports: $Exports<'flight-common/lib/components/FlightPanel'>;
}
declare module 'flight-common/lib/components/Footer.js' {
  declare module.exports: $Exports<'flight-common/lib/components/Footer'>;
}
declare module 'flight-common/lib/components/Header.js' {
  declare module.exports: $Exports<'flight-common/lib/components/Header'>;
}
declare module 'flight-common/lib/components/HelpPopover.js' {
  declare module.exports: $Exports<'flight-common/lib/components/HelpPopover'>;
}
declare module 'flight-common/lib/components/Icon.js' {
  declare module.exports: $Exports<'flight-common/lib/components/Icon'>;
}
declare module 'flight-common/lib/components/index.js' {
  declare module.exports: $Exports<'flight-common/lib/components/index'>;
}
declare module 'flight-common/lib/components/LicensableTable.js' {
  declare module.exports: $Exports<'flight-common/lib/components/LicensableTable'>;
}
declare module 'flight-common/lib/components/LicenseLink.js' {
  declare module.exports: $Exports<'flight-common/lib/components/LicenseLink'>;
}
declare module 'flight-common/lib/components/LicensesLinks.js' {
  declare module.exports: $Exports<'flight-common/lib/components/LicensesLinks'>;
}
declare module 'flight-common/lib/components/LinkContainer.js' {
  declare module.exports: $Exports<'flight-common/lib/components/LinkContainer'>;
}
declare module 'flight-common/lib/components/Links.js' {
  declare module.exports: $Exports<'flight-common/lib/components/Links'>;
}
declare module 'flight-common/lib/components/LoadingPage.js' {
  declare module.exports: $Exports<'flight-common/lib/components/LoadingPage'>;
}
declare module 'flight-common/lib/components/MissingNotice.js' {
  declare module.exports: $Exports<'flight-common/lib/components/MissingNotice'>;
}
declare module 'flight-common/lib/components/nav/NavCounter.js' {
  declare module.exports: $Exports<'flight-common/lib/components/nav/NavCounter'>;
}
declare module 'flight-common/lib/components/nav/NavCounterBadge.js' {
  declare module.exports: $Exports<'flight-common/lib/components/nav/NavCounterBadge'>;
}
declare module 'flight-common/lib/components/nav/NavOverlay.js' {
  declare module.exports: $Exports<'flight-common/lib/components/nav/NavOverlay'>;
}
declare module 'flight-common/lib/components/nav/NavOverlayEntry.js' {
  declare module.exports: $Exports<'flight-common/lib/components/nav/NavOverlayEntry'>;
}
declare module 'flight-common/lib/components/PageHeader.js' {
  declare module.exports: $Exports<'flight-common/lib/components/PageHeader'>;
}
declare module 'flight-common/lib/components/pages/AboutPage.js' {
  declare module.exports: $Exports<'flight-common/lib/components/pages/AboutPage'>;
}
declare module 'flight-common/lib/components/pages/index.js' {
  declare module.exports: $Exports<'flight-common/lib/components/pages/index'>;
}
declare module 'flight-common/lib/components/pages/PrivacyPolicyPage.js' {
  declare module.exports: $Exports<'flight-common/lib/components/pages/PrivacyPolicyPage'>;
}
declare module 'flight-common/lib/components/pages/SecurityPage.js' {
  declare module.exports: $Exports<'flight-common/lib/components/pages/SecurityPage'>;
}
declare module 'flight-common/lib/components/pages/TermsOfServicePage.js' {
  declare module.exports: $Exports<'flight-common/lib/components/pages/TermsOfServicePage'>;
}
declare module 'flight-common/lib/components/PrivacyPolicy.js' {
  declare module.exports: $Exports<'flight-common/lib/components/PrivacyPolicy'>;
}
declare module 'flight-common/lib/components/StandardModal.js' {
  declare module.exports: $Exports<'flight-common/lib/components/StandardModal'>;
}
declare module 'flight-common/lib/components/StatefulButton.js' {
  declare module.exports: $Exports<'flight-common/lib/components/StatefulButton'>;
}
declare module 'flight-common/lib/components/TimeAgo.js' {
  declare module.exports: $Exports<'flight-common/lib/components/TimeAgo'>;
}
declare module 'flight-common/lib/components/TooltipTrigger.js' {
  declare module.exports: $Exports<'flight-common/lib/components/TooltipTrigger'>;
}
declare module 'flight-common/lib/components/WrappedWithPara.js' {
  declare module.exports: $Exports<'flight-common/lib/components/WrappedWithPara'>;
}
declare module 'flight-common/lib/index.js' {
  declare module.exports: $Exports<'flight-common/lib/index'>;
}
declare module 'flight-common/lib/modules/notification/actions.js' {
  declare module.exports: $Exports<'flight-common/lib/modules/notification/actions'>;
}
declare module 'flight-common/lib/modules/notification/actionTypes.js' {
  declare module.exports: $Exports<'flight-common/lib/modules/notification/actionTypes'>;
}
declare module 'flight-common/lib/modules/notification/components/NotificationModal.js' {
  declare module.exports: $Exports<'flight-common/lib/modules/notification/components/NotificationModal'>;
}
declare module 'flight-common/lib/modules/notification/components/NotificationModals.js' {
  declare module.exports: $Exports<'flight-common/lib/modules/notification/components/NotificationModals'>;
}
declare module 'flight-common/lib/modules/notification/errorMessageCustomization.js' {
  declare module.exports: $Exports<'flight-common/lib/modules/notification/errorMessageCustomization'>;
}
declare module 'flight-common/lib/modules/notification/messageGeneration.js' {
  declare module.exports: $Exports<'flight-common/lib/modules/notification/messageGeneration'>;
}
declare module 'flight-common/lib/modules/notification/MessageGenerator.js' {
  declare module.exports: $Exports<'flight-common/lib/modules/notification/MessageGenerator'>;
}
declare module 'flight-common/lib/modules/notification/MessageGeneratorsMap.js' {
  declare module.exports: $Exports<'flight-common/lib/modules/notification/MessageGeneratorsMap'>;
}
declare module 'flight-common/lib/modules/notification/reducer.js' {
  declare module.exports: $Exports<'flight-common/lib/modules/notification/reducer'>;
}
declare module 'flight-common/lib/utils/console.js' {
  declare module.exports: $Exports<'flight-common/lib/utils/console'>;
}
declare module 'flight-common/lib/utils/licensables.js' {
  declare module.exports: $Exports<'flight-common/lib/utils/licensables'>;
}
declare module 'flight-common/lib/utils/momentConfiguration.js' {
  declare module.exports: $Exports<'flight-common/lib/utils/momentConfiguration'>;
}
declare module 'flight-common/lib/utils/silenceEvents.js' {
  declare module.exports: $Exports<'flight-common/lib/utils/silenceEvents'>;
}
declare module 'flight-common/src/components/AuthorizedComponent.js' {
  declare module.exports: $Exports<'flight-common/src/components/AuthorizedComponent'>;
}
declare module 'flight-common/src/components/Clipboard.js' {
  declare module.exports: $Exports<'flight-common/src/components/Clipboard'>;
}
declare module 'flight-common/src/components/CookieBanner.js' {
  declare module.exports: $Exports<'flight-common/src/components/CookieBanner'>;
}
declare module 'flight-common/src/components/CustomerSupport.js' {
  declare module.exports: $Exports<'flight-common/src/components/CustomerSupport'>;
}
declare module 'flight-common/src/components/FlightPanel.js' {
  declare module.exports: $Exports<'flight-common/src/components/FlightPanel'>;
}
declare module 'flight-common/src/components/Footer.js' {
  declare module.exports: $Exports<'flight-common/src/components/Footer'>;
}
declare module 'flight-common/src/components/Header.js' {
  declare module.exports: $Exports<'flight-common/src/components/Header'>;
}
declare module 'flight-common/src/components/HelpPopover.js' {
  declare module.exports: $Exports<'flight-common/src/components/HelpPopover'>;
}
declare module 'flight-common/src/components/Icon.js' {
  declare module.exports: $Exports<'flight-common/src/components/Icon'>;
}
declare module 'flight-common/src/components/index.js' {
  declare module.exports: $Exports<'flight-common/src/components/index'>;
}
declare module 'flight-common/src/components/LicensableTable.js' {
  declare module.exports: $Exports<'flight-common/src/components/LicensableTable'>;
}
declare module 'flight-common/src/components/LicenseLink.js' {
  declare module.exports: $Exports<'flight-common/src/components/LicenseLink'>;
}
declare module 'flight-common/src/components/LicensesLinks.js' {
  declare module.exports: $Exports<'flight-common/src/components/LicensesLinks'>;
}
declare module 'flight-common/src/components/LinkContainer.js' {
  declare module.exports: $Exports<'flight-common/src/components/LinkContainer'>;
}
declare module 'flight-common/src/components/Links.js' {
  declare module.exports: $Exports<'flight-common/src/components/Links'>;
}
declare module 'flight-common/src/components/LoadingPage.js' {
  declare module.exports: $Exports<'flight-common/src/components/LoadingPage'>;
}
declare module 'flight-common/src/components/MissingNotice.js' {
  declare module.exports: $Exports<'flight-common/src/components/MissingNotice'>;
}
declare module 'flight-common/src/components/nav/NavCounter.js' {
  declare module.exports: $Exports<'flight-common/src/components/nav/NavCounter'>;
}
declare module 'flight-common/src/components/nav/NavCounterBadge.js' {
  declare module.exports: $Exports<'flight-common/src/components/nav/NavCounterBadge'>;
}
declare module 'flight-common/src/components/nav/NavOverlay.js' {
  declare module.exports: $Exports<'flight-common/src/components/nav/NavOverlay'>;
}
declare module 'flight-common/src/components/nav/NavOverlayEntry.js' {
  declare module.exports: $Exports<'flight-common/src/components/nav/NavOverlayEntry'>;
}
declare module 'flight-common/src/components/PageHeader.js' {
  declare module.exports: $Exports<'flight-common/src/components/PageHeader'>;
}
declare module 'flight-common/src/components/pages/AboutPage.js' {
  declare module.exports: $Exports<'flight-common/src/components/pages/AboutPage'>;
}
declare module 'flight-common/src/components/pages/index.js' {
  declare module.exports: $Exports<'flight-common/src/components/pages/index'>;
}
declare module 'flight-common/src/components/pages/PrivacyPolicyPage.js' {
  declare module.exports: $Exports<'flight-common/src/components/pages/PrivacyPolicyPage'>;
}
declare module 'flight-common/src/components/pages/SecurityPage.js' {
  declare module.exports: $Exports<'flight-common/src/components/pages/SecurityPage'>;
}
declare module 'flight-common/src/components/pages/TermsOfServicePage.js' {
  declare module.exports: $Exports<'flight-common/src/components/pages/TermsOfServicePage'>;
}
declare module 'flight-common/src/components/PrivacyPolicy.js' {
  declare module.exports: $Exports<'flight-common/src/components/PrivacyPolicy'>;
}
declare module 'flight-common/src/components/StandardModal.js' {
  declare module.exports: $Exports<'flight-common/src/components/StandardModal'>;
}
declare module 'flight-common/src/components/StatefulButton.js' {
  declare module.exports: $Exports<'flight-common/src/components/StatefulButton'>;
}
declare module 'flight-common/src/components/TimeAgo.js' {
  declare module.exports: $Exports<'flight-common/src/components/TimeAgo'>;
}
declare module 'flight-common/src/components/TooltipTrigger.js' {
  declare module.exports: $Exports<'flight-common/src/components/TooltipTrigger'>;
}
declare module 'flight-common/src/components/WrappedWithPara.js' {
  declare module.exports: $Exports<'flight-common/src/components/WrappedWithPara'>;
}
declare module 'flight-common/src/index.js' {
  declare module.exports: $Exports<'flight-common/src/index'>;
}
declare module 'flight-common/src/modules/notification/actions.js' {
  declare module.exports: $Exports<'flight-common/src/modules/notification/actions'>;
}
declare module 'flight-common/src/modules/notification/actionTypes.js' {
  declare module.exports: $Exports<'flight-common/src/modules/notification/actionTypes'>;
}
declare module 'flight-common/src/modules/notification/components/NotificationModal.js' {
  declare module.exports: $Exports<'flight-common/src/modules/notification/components/NotificationModal'>;
}
declare module 'flight-common/src/modules/notification/components/NotificationModals.js' {
  declare module.exports: $Exports<'flight-common/src/modules/notification/components/NotificationModals'>;
}
declare module 'flight-common/src/modules/notification/errorMessageCustomization.js' {
  declare module.exports: $Exports<'flight-common/src/modules/notification/errorMessageCustomization'>;
}
declare module 'flight-common/src/modules/notification/messageGeneration.js' {
  declare module.exports: $Exports<'flight-common/src/modules/notification/messageGeneration'>;
}
declare module 'flight-common/src/modules/notification/MessageGenerator.js' {
  declare module.exports: $Exports<'flight-common/src/modules/notification/MessageGenerator'>;
}
declare module 'flight-common/src/modules/notification/MessageGeneratorsMap.js' {
  declare module.exports: $Exports<'flight-common/src/modules/notification/MessageGeneratorsMap'>;
}
declare module 'flight-common/src/modules/notification/reducer.js' {
  declare module.exports: $Exports<'flight-common/src/modules/notification/reducer'>;
}
declare module 'flight-common/src/utils/console.js' {
  declare module.exports: $Exports<'flight-common/src/utils/console'>;
}
declare module 'flight-common/src/utils/licensables.js' {
  declare module.exports: $Exports<'flight-common/src/utils/licensables'>;
}
declare module 'flight-common/src/utils/momentConfiguration.js' {
  declare module.exports: $Exports<'flight-common/src/utils/momentConfiguration'>;
}
declare module 'flight-common/src/utils/silenceEvents.js' {
  declare module.exports: $Exports<'flight-common/src/utils/silenceEvents'>;
}
