// flow-typed signature: f103e933fc87a662fa1c6e05d1237731
// flow-typed version: <<STUB>>/terminal.js_v^1.0.9/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'terminal.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'terminal.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'terminal.js/dist/terminal.dbg' {
  declare module.exports: any;
}

declare module 'terminal.js/dist/terminal' {
  declare module.exports: any;
}

declare module 'terminal.js/dist/terminal.min' {
  declare module.exports: any;
}

declare module 'terminal.js/Gruntfile' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/handler/chr' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/handler/csi' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/handler/dcs' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/handler/esc' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/handler/mode' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/handler/osc' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/handler/sgr' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/input/base' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/input/dom' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/input/tty' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/output/ansi' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/output/base' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/output/dom' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/output/html' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/output/live_base' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/output/plain' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/output/tty' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/source/base' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/source/emitter' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/term_diff' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/term_state' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/terminal' {
  declare module.exports: any;
}

declare module 'terminal.js/lib/util' {
  declare module.exports: any;
}

declare module 'terminal.js/test/ansi_output' {
  declare module.exports: any;
}

declare module 'terminal.js/test/common' {
  declare module.exports: any;
}

declare module 'terminal.js/test/dom_output' {
  declare module.exports: any;
}

declare module 'terminal.js/test/handler_sgi' {
  declare module.exports: any;
}

declare module 'terminal.js/test/html_output' {
  declare module.exports: any;
}

declare module 'terminal.js/test/plain_output' {
  declare module.exports: any;
}

declare module 'terminal.js/test/term_diff' {
  declare module.exports: any;
}

declare module 'terminal.js/test/term_state' {
  declare module.exports: any;
}

declare module 'terminal.js/test/terminal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'terminal.js/dist/terminal.dbg.js' {
  declare module.exports: $Exports<'terminal.js/dist/terminal.dbg'>;
}
declare module 'terminal.js/dist/terminal.js' {
  declare module.exports: $Exports<'terminal.js/dist/terminal'>;
}
declare module 'terminal.js/dist/terminal.min.js' {
  declare module.exports: $Exports<'terminal.js/dist/terminal.min'>;
}
declare module 'terminal.js/Gruntfile.js' {
  declare module.exports: $Exports<'terminal.js/Gruntfile'>;
}
declare module 'terminal.js/index' {
  declare module.exports: $Exports<'terminal.js'>;
}
declare module 'terminal.js/index.js' {
  declare module.exports: $Exports<'terminal.js'>;
}
declare module 'terminal.js/lib/handler/chr.js' {
  declare module.exports: $Exports<'terminal.js/lib/handler/chr'>;
}
declare module 'terminal.js/lib/handler/csi.js' {
  declare module.exports: $Exports<'terminal.js/lib/handler/csi'>;
}
declare module 'terminal.js/lib/handler/dcs.js' {
  declare module.exports: $Exports<'terminal.js/lib/handler/dcs'>;
}
declare module 'terminal.js/lib/handler/esc.js' {
  declare module.exports: $Exports<'terminal.js/lib/handler/esc'>;
}
declare module 'terminal.js/lib/handler/mode.js' {
  declare module.exports: $Exports<'terminal.js/lib/handler/mode'>;
}
declare module 'terminal.js/lib/handler/osc.js' {
  declare module.exports: $Exports<'terminal.js/lib/handler/osc'>;
}
declare module 'terminal.js/lib/handler/sgr.js' {
  declare module.exports: $Exports<'terminal.js/lib/handler/sgr'>;
}
declare module 'terminal.js/lib/input/base.js' {
  declare module.exports: $Exports<'terminal.js/lib/input/base'>;
}
declare module 'terminal.js/lib/input/dom.js' {
  declare module.exports: $Exports<'terminal.js/lib/input/dom'>;
}
declare module 'terminal.js/lib/input/tty.js' {
  declare module.exports: $Exports<'terminal.js/lib/input/tty'>;
}
declare module 'terminal.js/lib/output/ansi.js' {
  declare module.exports: $Exports<'terminal.js/lib/output/ansi'>;
}
declare module 'terminal.js/lib/output/base.js' {
  declare module.exports: $Exports<'terminal.js/lib/output/base'>;
}
declare module 'terminal.js/lib/output/dom.js' {
  declare module.exports: $Exports<'terminal.js/lib/output/dom'>;
}
declare module 'terminal.js/lib/output/html.js' {
  declare module.exports: $Exports<'terminal.js/lib/output/html'>;
}
declare module 'terminal.js/lib/output/live_base.js' {
  declare module.exports: $Exports<'terminal.js/lib/output/live_base'>;
}
declare module 'terminal.js/lib/output/plain.js' {
  declare module.exports: $Exports<'terminal.js/lib/output/plain'>;
}
declare module 'terminal.js/lib/output/tty.js' {
  declare module.exports: $Exports<'terminal.js/lib/output/tty'>;
}
declare module 'terminal.js/lib/source/base.js' {
  declare module.exports: $Exports<'terminal.js/lib/source/base'>;
}
declare module 'terminal.js/lib/source/emitter.js' {
  declare module.exports: $Exports<'terminal.js/lib/source/emitter'>;
}
declare module 'terminal.js/lib/term_diff.js' {
  declare module.exports: $Exports<'terminal.js/lib/term_diff'>;
}
declare module 'terminal.js/lib/term_state.js' {
  declare module.exports: $Exports<'terminal.js/lib/term_state'>;
}
declare module 'terminal.js/lib/terminal.js' {
  declare module.exports: $Exports<'terminal.js/lib/terminal'>;
}
declare module 'terminal.js/lib/util.js' {
  declare module.exports: $Exports<'terminal.js/lib/util'>;
}
declare module 'terminal.js/test/ansi_output.js' {
  declare module.exports: $Exports<'terminal.js/test/ansi_output'>;
}
declare module 'terminal.js/test/common.js' {
  declare module.exports: $Exports<'terminal.js/test/common'>;
}
declare module 'terminal.js/test/dom_output.js' {
  declare module.exports: $Exports<'terminal.js/test/dom_output'>;
}
declare module 'terminal.js/test/handler_sgi.js' {
  declare module.exports: $Exports<'terminal.js/test/handler_sgi'>;
}
declare module 'terminal.js/test/html_output.js' {
  declare module.exports: $Exports<'terminal.js/test/html_output'>;
}
declare module 'terminal.js/test/plain_output.js' {
  declare module.exports: $Exports<'terminal.js/test/plain_output'>;
}
declare module 'terminal.js/test/term_diff.js' {
  declare module.exports: $Exports<'terminal.js/test/term_diff'>;
}
declare module 'terminal.js/test/term_state.js' {
  declare module.exports: $Exports<'terminal.js/test/term_state'>;
}
declare module 'terminal.js/test/terminal.js' {
  declare module.exports: $Exports<'terminal.js/test/terminal'>;
}
